In [1]:
import copy, math
import numpy as np
import matplotlib.pyplot as plt
np.set_printoptions(precision = 2)

In [3]:
X_train = np.array([[2104, 5,1,45],[1416,3,2,40],[852,2,1,35]])
Y_train = np.array([460,232,178])

In [11]:
print(f"X_shape = {X_train.shape}\nY_shape = {Y_train.shape}\n")
print(f"X_train = \n{X_train}\nY_train = \n{Y_train}")
print(type(X_train))
print(type(Y_train))

X_shape = (3, 4)
Y_shape = (3,)

X_train = 
[[2104    5    1   45]
 [1416    3    2   40]
 [ 852    2    1   35]]
Y_train = 
[460 232 178]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [43]:
b_init = 785.1811367994083
w_init = np.array([0.39133535,18.75376741,-53.36032453,-26.42131618])

In [44]:
#Computes the predicted value for one training example by multiplying all w[i] and corresponding x[i] then adding b
#p = np.dot(x,w) + b
def predict_single_loop(x, w, b):
    n = x.shape[0]
    p = 0
    for i in range(n):
        p_i = x[i]*w[i]
        p = p + p_i
    p = p + b
    return p

In [45]:
x_vec = X_train[0,:] #extracting 1 training example
print(f"x_vec:\n{x_vec}\nx_vec.shape:\n{x_vec.shape}")

f_wb = predict_single_loop(x_vec,w_init,b_init) #result is scalar
print(f"prediction: {f_wb}")

x_vec:
[2104    5    1   45]
x_vec.shape:
(4,)
prediction: 459.9999976194083


In [46]:
def predict(x, w, b):
    p = np.dot(x,w) + b
    return p

In [47]:
x_vec = X_train[0,:]
f_wb = predict(x_vec,w_init,b_init)
print(f"prediction: {f_wb}")

prediction: 459.9999976194083


In [48]:
#now lets compute cost J for multivars
def compute_cost(x,y,w,b):
    m = x.shape[0]
    error = 0
    cost = 0
    for i in range(m):
        f_wb_i = np.dot(x[i,:],w) + b #scalar
        error = (f_wb_i - y[i])**2 #scalar
        cost += error  #scalar
    cost = cost/(2*m)
    return cost

In [49]:
cost = compute_cost(X_train,Y_train, w_init, b_init)
print(f"Optimum Cost: {cost}")

Optimum Cost: 1.5578904428966628e-12


In [52]:
def compute_gradient(X, y, w, b):
    m, n = X.shape
    dj_dw = np.zeros((n,)) #nafs 3adad el features
    dj_db = 0.
    #summation all over training examples
    for i in range(m):
        #Calculate training example error
        err = (np.dot(X[i],w) + b) - y[i]
        #Update all parameters
        for j in range(n):
            dj_dw[j] = dj_dw[j] + err * X[i,j]
        #Update b
        dj_db = dj_db + err
    #keda m3ana el summations mt5azena f vector dj_dw w float dj_db
    dj_dw = dj_dw / m
    dj_db = dj_db / m
    
    return dj_dw, dj_db

In [53]:
tmp_dj_dw, tmp_dj_db = compute_gradient(X_train, Y_train, w_init, b_init)
print(f"{tmp_dj_dw}, {tmp_dj_db}")

[-2.73e-03 -6.27e-06 -2.22e-06 -6.92e-05], -1.6739251501955248e-06
